language: php

php:
  - 7.0

install:
  - composer selfupdate
  - composer install

script:
  - ./vendor/bin/php-cs-fixer fix --diff --dry-run
  - ./vendor/bin/phpcs -s
  - ./vendor/bin/phpunit --colors